# Agent 5/6 â€” ESG Scoring & Climate

**What this notebook does:**  
Takes the raw ESG numbers from the provided datasets and converts them into clean, comparable scores (0â€“100) for E (Environmental), S (Social), G (Governance), and a combined ESG score. Pillar weights are sector-specific, calibrated to SASB materiality standards.

**Why we don't just use one vendor ESG score:**  
Academic research (Berg, Koelbel & Rigobon 2022 â€” *Aggregate Confusion*) shows that ESG scores from different vendors disagree significantly. So we build our own transparent score from raw variables â€” this way we can explain every number to the investor panel.

**Why SASB materiality?**  
Applying the same E/S/G weights to every company ignores sector context. SASB identifies which ESG factors are financially material per industry â€” we use these to set pillar weights before scoring.

**How to present this to investors:**  
> *Rather than relying on a black-box third-party ESG rating, we constructed our own transparent score from raw environmental, social, and governance variables. Pillar weights are calibrated to SASB materiality standards so that, for example, an energy company is judged primarily on its environmental performance while a bank is judged primarily on governance quality.*

In [1]:
import pandas as pd
import numpy as np
from datetime import date
import glob

# Load master dataset from notebook 01
master_files = sorted(glob.glob("../outputs/scores/master_dataset_*.csv"))
if not master_files:
    raise FileNotFoundError("Run notebook 01 first to create the master dataset.")

master = pd.read_csv(master_files[-1])
print(f"Master dataset loaded: {len(master)} companies")
print("Columns available:", list(master.columns))

Master dataset loaded: 279 companies
Columns available: ['rc', 'idBbGlobal', 'idBbUnique', 'idBbCompany', 'idBbGlobalCompany', 'idBbGlobalCompanyName', 'idBbSecNumDes', 'ticker', 'exchCode', 'idIsin', 'idCusip', 'idSedol1', 'securityTyp', 'securityTyp2', 'classificationLevelCode1', 'classificationLevelName1', 'classificationLevelCode2', 'classificationLevelName2', 'classificationLevelCode3', 'classificationLevelName3', 'classificationLevelCode4', 'classificationLevelName4', 'classificationLevelCode5', 'classificationLevelName5', 'classificationLevelCode6', 'classificationLevelName6', 'classificationLevelCode7', 'classificationLevelName7', 'classificationScheme', 'rank', 'company', 'return_5y_pct', 'return_10y_pct', 'bb_ticker', 'yf_ticker', 'excluded', 'latestPeriodEndCsr', 'esgDisclosureScore', 'socialDisclosureScore', 'environDisclosureScore', 'directCo2Emissions', 'indirectCo2Emissions', 'totalCo2Emissions', 'totalGhgEmissions', 'scp3BusinessTravelEmissions', 'gasFlaring', 'emissionReduction', 'climateChgProds', 'climateChgPolicy', 'percentOfDisclosure', 'scopeOfDisclosure', 'scope1_emissions_tco2e', 'ghgScope2', 'ghgScope3', 'climateChgOpportunities', 'climateRisks', 'methaneEmissions', 'dirPfcEmissionsInCo2Equiv', 'carbonPerUnitOfProd', 'carbon_intensity_tco2e_per_eur_m_revenue', 'totalGhgCo2Emissions', 'scopeGhgCo2Emissions1', 'scopeGhgCo2Emissions2', 'totGhgCo2EmIntensPerSales', 'scopeGhgCo2EmIntensPerSles1', 'scopeGhgCo2EmIntensPerSles2', 'totGhgCo2EmIntensPerEnrgy', 'totGhgCo2EmIntensPerEmp', 'totGhgCo2EmIntensPerAst', 'totGhgCo2EmIntPerGrFxdAst', 'totGhgCo2EmIntPerNtFxdAst', 'embeddedCarbonTotalReserves', 'ghgIntensityPerSales', 'ghgIntensityPerEmployee', 'co2IntensityPerEmployee', 'ghgIntensityPerAssets', 'co2IntensityPerAssets', 'ghgScopeIntensityPerSales1', 'ghgScopeIntensityPerSales2', 'travelEmissionsPerSales', 'ghgIntensityPerRpm', 'odsEmissions', 'directSf6Emissions', 'dirMethaneEmInCo2Equiv', 'dirHfcEmissionsInCo2Equiv', 'dirSf6EmissionsInCo2Equiv', 'noxEmissions', 'so2Emissions', 'vocEmissions', 'carbonMonoxideEmissions', 'particulateEmissions', 'sulphurOxideEmissions', 'directNitrousOxideEmissions', 'dirN2oEmInCo2Equiv', 'carbonOffsets', 'noxEmissionsPerSales', 'soxEmissionsPerSles', 'energyConsumption', 'renewable_energy_pct', 'energyEfficPolicy', 'electricityUsed', 'coalUsed', 'natGasUsed', 'oilDieselUsed', 'purchasedElectricity', 'purchasedElecTotRenewables', 'nuclearPctEnergy', 'solarPctEnergy', 'totalPowerGenerated', 'wasteEnergyProduction', 'coalEnergyProduction', 'hydroEnergyProduction', 'windEnergyProduction', 'solarEnergyProduction', 'biomassEnergyProduction', 'totalRenewablesEnergyProd', 'fossilFuelsEnergyProduction', 'fossilFuelsPctEnergyCapacity', 'nuclearPctEnergyCapacity', 'totRenewablesPctEnergyCapacity', 'electricityGenCapacityTotMw', 'renewableElectricityTargetPol', 'energyPerUnitProduction', 'energyIntensityPerSales', 'energyIntensityPerEbitda', 'energyIntensityPerEmployee', 'energyIntensityPerAssets', 'fuelConsumptionPerRpm', 'totalWaterUse', 'pctWaterRecycled', 'dischargeToWater', 'totalWaterDischarged', 'waterPerUnitOfProd', 'municipalWaterUse', 'totalWaterRecycled', 'codOfDischarges', 'bodOfDischarges', 'waterPolicy', 'water_withdrawal_m3', 'processWaterUse', 'surfaceWaterWithdrawals', 'groundwaterWithdrawals', 'saltWaterWithdrawals', 'reclaimedWaterUse', 'coolingWaterInflow', 'coolingWaterOutflow', 'waterDischargePct', 'waterUseWithdrawal', 'h2oUseWthdrlIntensSales', 'h2oUseWthdrlIntensEmpl', 'h2oUseWthdrlIntensAssets', 'waterIntensityPerSales', 'waterIntensityPerEmployee', 'waterIntensityPerAssets', 'waterUsageEfficiencyRt', 'waterStressExposurePct', 'hazardousWaste', 'totalWaste', 'wasteRecycled', 'paperConsumption', 'rawMatUsed', 'pctRecycledMaterials', 'wasteReduction', 'sustainPackaging', 'wasteSentToLandfills', 'paperRecycled', 'miningOverburden', 'tailingsWaste', 'pctRawMaterialSustainSrc', 'wasteIntensityPerEmployee', 'wasteGeneratedPerAssets', 'wasteGeneratedPerSales', 'paperConsumptionPerSales', 'numberSpills', 'numEnvironFines', 'environFinesAmt', 'isoSites14001', 'greenBuilding', 'environQualMgt', 'investmentsInSustainability', 'amountOfSpills', 'pctSitesCertified', 'biodiversityPolicy', 'hydrocarbonSpills', 'environSupplyMgt', 'numberEmployeesCsr', 'numberOfPartTimeEmployees', 'numberOfTemporaryEmployees', 'employee_turnover_pct', 'pctEmployeesUnionized', 'humanRightsPolicy', 'trainingPolicy', 'fairRemunerationPolicy', 'employeeTrainingCost', 'totHrsSpentByFirmEmpTrain', 'policyAgainstChildLabor', 'trainingSpendPerEmployee', 'genderPayGapBreakout', 'women_on_board_pct', 'women_in_workforce_pct', 'pctMinorityMgt', 'pctMinorityEmployees', 'equalOpportunityPolicy', 'employeeAverageAge', 'pctDisabledInWorkforce', 'womenManagementToEmplRatio', 'customerComplaints', 'intellectualPptyRghtsProtPol', 'qualityAssuranceAndRecallPol', 'consumerDataProtectionPolicy', 'communitySpendPctPretaxProfit', 'communitySpendPctEbitda', 'communitySpendPctEquity', 'suppliersAudited', 'supplierAuditsConducted', 'socialSupplyChainMgmt', 'supplierFacilitiesAudited', 'susSupGdlEncEsgAreaPubDis', 'workAccidentsEmployees', 'lostTimeAccidents', 'lostTimePerEmployee', 'fatalitiesContractors', 'fatalitiesEmployees', 'fatalitiesTotal', 'healthSafetyPolicy', 'lostTimeIncidentRate', 'work_related_injury_rate', 'fatalitiesThirdParty', 'totalAccidentsContractors', 'lostTimeIncidentRtCntrctr', 'totRecordableIncidRtCntrctr', 'fatalityRateWorkforce', 'accidentsPerEmployees1000', 'communitySpending', 'politicalDonations', 'ethicsPolicy', 'griCompliance', 'verificationType', 'numberOfSites', 'environmentalAcctgCost', 'sustnbleEsgAum', 'unGlobalCompactSignatory', 'employeeCsrTraining', 'unPriSignatory', 'empProtWhistleBlowerPolicy', 'antiBriberyEthicsPolicy', 'consistentReportingBasis', 'equatorPrinciplesSignatory', 'sriAssetsPctTotalAum', 'polDonationsPctPretaxProfit', 'noxIntensityPerPowerGen', 'so2SoxIntensityPerPowerGen', 'noxIntensityPerMboe', 'sulphurDioxideSulphurOxideEm', 'so2SoxIntensityPerMboe', 'noxIntensPerRevPsngrMiKms', 'so2SoxIntensRevPsgrMiKms', 'travelCo2PerEmployee', 'ghgIntensityPerEnergy', 'totGhgCo2EmissIntensityMboe', 'totGhgCo2EmIntensPerRpm', 'ghgIntensityPerMboe', 'co2IntensityPerMboe', 'co2IntensityPerVehicle', 'ghgCo2IntensityPerPowerGen', 'ghgIntensityPerPowerGen', 'ghgIntensityPerVehicle', 'gasFlaringPerMboe', 'ghgScopeIntensPerPwrGen1', 'totGhgCo2EmIntensPerVehSld', 'totGhgCo2EmIntensPerElecSld', 'co2IntensityPerKwhSold', 'totGhgCo2EmIntensPsfMeter', 'co2IntensityPerPowerGen', 'embeddedCarbonCoalReserves', 'embeddedCarbonOilReserves', 'embeddedCarbonGasReserves', 'ghgIntensityPerElecSold', 'co2IntensityPerSqFt', 'co2IntensityPerRpm', 'ghgIntensityPerSqFt', 'co2EmMilMtUnderEuEts', 'co2EmLesAllowMilMtUndEuEts', 'co2AllowMilMtUnderEuEts', 'co2IntensityPerGwhSold', 'ghgIntensityPerGwhSold', 'energyIntensityPerMboeProd', 'energyIntensityPerSqFt', 'nuclearEnergyProduction', 'co2IntensityPerEnergyConsmd', 'energyIntensityPerVehicle', 'gasEnergyProduction', 'coalPctEnergyCapacity', 'electricityProdThermOilGwh', 'fossilFuelsPctEnergyProduction', 'hydroPctEnergyProduction', 'totalRenewablesEnergyCapacity', 'enrgyIntensRevPsngrMiKms', 'biomassFuelUsePercentage', 'renewableEnergyCertificates', 'alternativeFuelUsePct', 'coalPctEnergyProduction', 'totRenewablesPctEnergyProd', 'gasPctEnergyProduction', 'windPctEnergyProduction', 'wastePctEnergyProduction', 'biomassPctEnergyProduction', 'solarPctEnergyCapacity', 'othRenewablesPctEnergyCapacity', 'selfGenRenewableElectricity', 'hydroPctEnergyCapacity', 'powerPurchaseAgreement', 'gasPctEnergyCapacity', 'windPctEnergyCapacity', 'hydroEnergyCapacity', 'nuclearEnergyCapacity', 'biomassPctEnergyCapacity', 'wastePctEnergyCapacity', 'windEnergyCapacity', 'fossilFuelsEnergyCapacity', 'solarEnergyCapacity', 'wasteEnergyCapacity', 'purchasedElectricityCoal', 'purchasedElectricityGas', 'purchasedElecFossilFuels', 'purchasedElectricityNuclear', 'purchasedElectricityHydro', 'purchasedElectricityWind', 'purchasedElectricitySolar', 'purchasedElectricityBiomass', 'purchasedElectricityWaste', 'purchasedElecOthRenewables', 'otherRenewablesEnergyCapacity', 'biomassEnergyCapacity', 'elecGenCapRenewGeothermalMw', 'coalEnergyCapacity', 'elecProdRenewGeothermalGwh', 'otherRenewablesPctEnergyProd', 'gasEnergyCapacity', 'elecGenCapThermCoalOrLcMw', 'electricityGenCapGeothermalPct', 'electricityGenCapThermOilMw', 'elecGenCapThermMultifuelMw', 'otherRenewablesEnergyProd', 'elecProdThermCoalOrLcGwh', 'elecGenCapThOthNonRenewMw', 'elecProdThermOthNonRenewGwh', 'elecGenCapThermCoalOrLigMw', 'elecProdThermMultifuelGwh', 'electricityProdThermChpGwh', 'electricityGenCapThermOilPct', 'electricityGenCapThermChpMw', 'elecProdThermCoalOrLigGwh', 'elecGenCapOthNonRenewPct', 'elecGenCapThermLignitePct', 'electricityGenCapThermChpPct', 'elecGenCapThermMultiPct', 'electGenProdThermOilPct', 'coalOrLigPctEnergyProduction', 'electGenProdOthNonRenewPct', 'electGenProdThermMultiPct', 'electGenProdGeothermalPct', 'electGenProdThermChpPct', 'electGenProdThermLignitePct', 'paperConsumptionPerEmployee', 'wasteGeneratedPerVehicle', 'drillingWaste', 'waterIntensityPerEnergy', 'waterIntensityPerMboe', 'waterUsePerPowerGenerated', 'waterIntensityPerVehicle', 'h2oUseWthdrlIntensEnrgConsm', 'waterIntensityPerSqFt', 'h2oUseWthdrlIntensMboe', 'h2oUseWthdrlIntensPowerGen', 'freshwaterWithdrawals', 'pctFreshwaterTotH2oWithdrawn', 'waterConsmptn', 'rainwtrHarvstd', 'divrtdWaterForGenrtnOfHydrpwr', 'divrtdWaterExHydrpwrGenrtn', 'pctOfWaterRecycldPerTotlWaterUsed', 'totlWaterConsmptn', 'gender_pay_gap_pct', 'pctGenderPayGapMidOthMgmt', 'pctGenderPayGapEmplExMgmt', 'pctGenderPayGapSenMgmt', 'bbbeeRatingLevel', 'bbbeeOverallScore', 'bbbeeAndBlackHdsaOwnershipPct', 'percentageSuppliersAudited', 'pctOfSuppliersInNonCompl', 'sustainDevGoalsTgtPol', 'taxesPaidToGovernments', 'spillsPerMboe', 'numSignifEnvironmentalFines', 'amountOfSignfcntEnvrnmntlFines', 'numberSignificantSpills', 'amountOfSignfcntSpills', 'lostTmIncidentRtWorkforce', 'totRecrdblIncidRtWorkforce', 'fatalitiesPerEmpl1000', 'fatalitiesPerContractors1000', 'numberOfContractors', 'voluntaryTurnoverPct', 'involuntaryTurnoverPct', 'training_hours_per_employee', 'scope2MktBasedGhgEmissions', 'totMktBasedGhgEmissions', 'indrctMarktBasedCarbonDioxide', 'totlMarktBasedCarbonDioxide', 'class', 'fiscalYearPeriod', 'totFuelConsumed', 'biomassFuelUsed', 'altrntveFuelUsed', 'selfGenrtdTotlEnrgy', 'selfGenrtdEnrgyNonRenwble', 'nmfrEmployees', 'nmfrContractors', 'nmfrWorkforce', 'occupationalDiseaseRtEmpl', 'occupationalDiseaseRtCntrctr', 'occupDiseaseRtWorkforce', 'vehicleIncidentRtEmployees', 'vehIncidentRateCntrctr', 'vehicleIncidentRtWorkforce', 'climateScenarioAnalysis', 'carbonPricing', 'wastewtrTreated', 'wastewaterManagementPolicy', 'wasteDivertedLandfill', 'waste_recycled_pct', 'amtWasteComposted', 'amtWasteIncinerated', 'susAcctgStandardsBrdRptComp', 'pctRenewableEnergyConsmd', 'numberSitesEsa', 'landDisturbed', 'landRestored', 'pctLandRestored', 'emergResponsePreparedness', 'pctPortfolioEnergyRtg', 'pctOfFloorAreaCovrdByEnrgyCertficatn', 'numCorruptionLegalCases', 'numberFinesBriberyAndCorrupt', 'amountFinesBriberyAndCorrupt', 'thirdPartyCertfidForestlnd', 'modrnSlaveryStatemnt', 'supplyChainModrnSlaveryAssessmnt', 'mangnseEmissns', 'leadEmissns', 'polycyclcAromtcHydrcrbnEmissns', 'mercryHgEmissns', 'pm10Emissions', 'dioxinsAndFurans', 'cadmiumEmissions', 'hazrdsAirPolltntsEmissns', 'scope3OthrDwnstrmEmissns', 'scope3OthrUpstrmEmissns', 'scope3PurchsdGoodsAndServcsEmissns', 'scope3CapitlGoodsEmissns', 'scope3FuelAndEnrgyActvtsNotInScope1OrScope2Emissns', 'scope3UpstrmTransprttnAndDistrbtnEmissns', 'scope3WasteGenrtdInOprtnsEmissns', 'scope3EmplyeeCommtngEmissns', 'scope3UpstrmLeaseAsstsEmissns', 'scope3DwnstrmTransprttnAndDistrbtnEmissns', 'scope3ProcessngOfSoldProdctsEmissns', 'scope3UseOfSoldProdctsEmissns', 'scope3EolTreatmntOfSoldProdctsEmissns', 'scope3DwnstrmLeasdAsstsEmissns', 'scope3EmissnsFromFranchss', 'scope3EmissnsFromInvstmnts', 'scope3EmissnsOthr', 'compnyClaimsScinceBasedEmissnsTargts', 'compnyClaimsNetZeroEmissnsTgt', 'baselineYrGhgEmissionsTgt', 'tgtYrGhgEmissionsTgt', 'ghgEmissIntensReductTgt', 'ghgEmissionsReductTgtAbs', 'ghgEmissionsAbsReductTgt', 'pctGhgEmRedAchAgaTgt', 'scope1GhgTgtBaselineYr', 'scope1GhgTgtTgtYr', 'scope1EmissReductTgtIntens', 'scope1EmissReductTgtAbs', 'scope1EmissAbsReductTgt', 'pctRedAchSc1EmRedTgt', 'pctWomeninMidandofOtherMgmt', 'latestPeriodEndCsr_gov', 'govnceDisclosureScore', 'ceo_pay_ratio', 'totSalariesPaidToCeoAndEquiv', 'totBonusesPaidToCeoAndEquiv', 'allOtherCompAwToCeoAndEquiv', 'totStkAwdGivenToCeoAndEquiv', 'totOptAwdGivenToCeoAndEquiv', 'totNonEqtIncentGvnToCeoAndEq', 'tPenAndNqDefPenGvnCeoAndEq', 'totOtherCompAwToCeoAndEquiv', 'totSalAndBnsAwToCeoAndEquiv', 'totCompAwToCfoAndEquiv', 'totSalariesPaidToCfoAndEquiv', 'totBonusesPaidToCfoAndEquiv', 'allOtherCompAwToCfoAndEquiv', 'totSalAndBnsAwToCfoAndEquiv', 'totCompAwToCooAndEquiv', 'totCompAwToCioAndEquiv', 'totCompensationAwToExecs', 'totSalariesPaidToExecutives', 'totalBonusesPaidToExecutives', 'allOtherCompAwToExecs', 'totStkAwardsGivenToExecs', 'totOptionAwardsGivenToExecs', 'totNonEqtyIncentGivenToExecs', 'tPenAndNqDefPenGvnToExecs', 'totOtherCompAwToExecs', 'totSalariesAndBnsPdToExecs', 'numCeoAndEquivIncCompPdDurFy', 'numCfoAndEquivIncCompPdDurFy', 'numExecutivesIncCompPdDurFy', 'totalBodCompensationAwarded', 'totalBodFeesPaidInCash', 'totalBodStockAwardsGiven', 'numDirectorsIncCompPdDurFy', 'averageBodTotalCompensation', 'pctBodCompPdInStkAwd', 'avgExecutiveTotCompensation', 'avgExecSalaryPlusBonusAmt', 'totExecPayAsPctTotPsnlExp', 'totExecPayAsPctSgandaNetRandd', 'totalExecPayAsPctOpex', 'outsideCompAdvisorsAppt', 'feesPdToCompConsultants', 'pctOfIndDirectorsOnCompCmte', 'indCompCmteChairperson', 'numOfCompensationCommitteeMtg', 'compensationCmteMtgAttendPct', 'clawbackProvisionForExecComp', 'execComConsultantSvcProvided', 'execCompAdvFeesPdToComAdv', 'pctOfCompAdvFeesPdToComAdv', 'chgOfCtrlBfitGoldChuteAgr', 'frequencyOfSayOnPayVotes', 'sayOnPayProvision', 'sayPayNumberOfVotesFor', 'sayPayNumberOfVotesAgainst', 'sayPaySupportLevel', 'sayOnPayNumberVotesAbstain', 'sayPayNumVotesBrkNonVote', 'numOfCeoAndEquivChngDurFy', 'numOfCioAndEquivChngDurFy', 'numOfCfoAndEquivChngDurFy', 'numOfCooAndEquivChngDurFy', 'numOfExecutiveChangesDuringFy', 'numberOfBodChangesDuringFy', 'dateOfLastBodChange', 'ceoTenureAsOfFyEnd', 'cfoTenureAsOfFyEnd', 'cooTenureAsOfFyEnd', 'boardDuration', 'executiveDirectorBoardDur', 'presidingDirector', 'classifiedBoardSystem', 'unitaryOrTwoTierBoardSystem', 'corpExecutiveOfficerSysInd', 'pctOfCorpExecOffAlsoOnBod', 'boardAgeLimit', 'board_independence_pct', 'independentLeadDirector', 'independentChairperson', 'assuranceAuditor', 'auditCommitteeMeetings', 'auditorRatification', 'yearsAuditorEmployed', 'sizeOfBoardOfCorpAuditors', 'numberOfOutsideCorpAuditors', 'numberOfIndCorpAuditors', 'audit_committee_independence_pct', 'indAuditCommitteeChairperson', 'auditCommitteeMeetingAttendPct', 'pctOfIndDirectorsOnNomCmte', 'executive_pay_esg_linked_pct', 'sustainInvToCapex', 'esgLinkedCompensationForBrd', 'nonexecDirWithResponsForCsr', 'execDirWithResponsForCsr', 'pctOwnershipReqForSpecialMtg', 'poisonPillPlan', 'shareholderApprovedPoisonPill', 'poisonPillTideProvision', 'poisonPillSunsetProvision', 'pctPoisonPillTrigThreshold', 'blankCheckPreferredAuthorized', 'dualClassUnequalVtgRts', 'uneqVtgRtsStksIssdIncPfd', 'cumulativeVotingSystem', 'poisonPillExpirationDate', 'indNominationCmteChairperson', 'numOfNominationCommitteeMtg', 'nominationCmteMtgAttendPct', 'boardMeetingsPerYr', 'boardMeetingAttendancePct', 'numOfDirAttendLtPctOfMtg75', 'indDirectorsBrdMtgAttendPct', 'bodNomineesLegalProceedings', 'cioTenureAsOfFyEnd', 'auditorRatificationNumVotes', 'auditorRatifNumVotesAga', 'auditorRatificationSupLevl', 'auditRatifNumVotesAbstain', 'audRatifNumVotesBrkNonVote', 'auditFinancialExpert', 'companyConductsBrdEvaluations', 'companyHasProxyAccessPolicy', 'proxyAccessPctSeatAccess', 'proxyAccessOwnershipReq', 'proxyAccessReqHldgPer', 'proxyAccessMaxShrhldrBlock', 'directorElectionVotePolicy', 'controlledCompany', 'companyHasAntiPledgingPolicy', 'compnyExctveOrDirctrPledgdShares', 'compHasExecShOwnerGuidelns', 'directorShOwnershipGuidelines', 'csrSustainabilityCommittee', 'class_gov', 'fiscalYearPeriod_gov', 'legalEntityIdentifier', 'eqyFiscalYrEnd', 'latestPeriodEndCsr_tax', 'pctOfEuTaxnmyEligbleRevenue', 'amountOfEuTaxnmyEligbleRevenue', 'pctOfRevenuePotntiallyAligndWithEuTaxnmy', 'amountOfRevenuePotntiallyAligndWithEuTaxnmy', 'euTaxnmyPotntiallyAligndMitgtnPctRevenue', 'euTaxnmyPotntiallyAligndMitgtnAmountRevenue', 'euTaxnmyPotntiallyAligndAdapttnPctRevenue', 'euTaxnmyPotntiallyAligndAdapttnAmountRevenue', 'euTaxnmyEstmatdSubstantlContrbtnWaterPctRevenue', 'euTaxnmyEstmatdSubstantlContrbtnWaterAmountRevenue', 'euTaxnmyEstmatdSubstantlContrbtnWastePctRevenue', 'euTaxnmyEstmatdSubstantlContrbtnWasteAmountRevenue', 'euTaxnmyEstmatdSubstantlContrbtnPolltnPctRevenue', 'euTaxnmyEstmatdSubstantlContrbtnPolltnAmountRevenue', 'euTaxnmyEstmatdSubstantlContrbtnBiodiverstyPctRevenue', 'euTaxnmyEstmatdSubstantlContrbtnBiodiverstyAmountRev', 'euTaxnmyEstmatdDnshMitgtnLevl1', 'euTaxnmyEstmatdDnshMitgtnLevl2', 'euTaxnmyEstmatdDnshAdapttnLevl1', 'euTaxnmyEstmatdDnshAdapttnLevl2', 'euTaxnmyEstmatdDnshWaterLevl1', 'euTaxnmyEstmatdDnshWaterLevl2', 'euTaxnmyEstmatdDnshWasteLevl1', 'euTaxnmyEstmatdDnshWasteLevl2', 'euTaxnmyEstmatdDnshPolltnLevl1', 'euTaxnmyEstmatdDnshPolltnLevl2', 'euTaxnmyEstmatdDnshBiodiverstyLevl1', 'euTaxnmyEstmatdDnshBiodiverstyLevl2', 'euTaxnmyMssEstmatd', 'euTaxnmyMssOptEstmatd', 'euTaxnmyEligbleRevenuePct', 'euTaxnmyEligbleRevenueAmount', 'euTaxnmyEligbleCapexPct', 'euTaxnmyEligbleCapexAmount', 'euTaxnmyEligbleOpexPct', 'euTaxnmyEligbleOpexAmount', 'pctOfRevenueAligndWithEuTaxnmy', 'amountOfRevenueAligndWithEuTaxnmy', 'pctOfCapexAligndWithEuTaxnmy', 'amountOfCapexAligndWithEuTaxnmy', 'euTaxnmyAligndOpexPct', 'euTaxnmyAligndOpexAmount', 'verificationType_tax', 'indpndntAssessmntCondctd', 'data_vintage']

## Step 0 â€” SASB Materiality Weights

The Sustainability Accounting Standards Board (SASB) identifies which ESG factors are **financially material** for each industry sector. Rather than applying the same E/S/G pillar weights to every company, we adjust the weights based on the sector each company operates in.

**Why this matters:** A bank and an oil company should not be scored on the same ESG priorities. For an oil company, the Environmental pillar dominates. For a bank, Governance (data security, systemic risk, executive pay) is most material.

| Sector | E weight | S weight | G weight | Key SASB rationale |
|--------|----------|----------|----------|--------------------|
| Technology | 25% | 35% | 40% | Data security, employee engagement, governance |
| Financials | 20% | 35% | 45% | Systemic risk, data privacy, governance quality |
| Energy | 55% | 25% | 20% | GHG emissions, water, spills dominate |
| Consumer Discretionary | 35% | 40% | 25% | Supply chain labour, product safety |
| Consumer Staples | 35% | 40% | 25% | Supply chain, packaging, labour practices |
| Health Care | 25% | 40% | 35% | Patient safety, access, product quality |
| Industrials | 45% | 35% | 20% | GHG, occupational health, waste |
| Materials | 50% | 30% | 20% | Air/water pollution, hazardous waste |
| Real Estate | 45% | 25% | 30% | Energy efficiency, water management |
| Communication Services | 20% | 40% | 40% | Data privacy, content governance, diversity |
| Utilities | 50% | 25% | 25% | GHG intensity, renewable mix, water |
| Default (unmatched) | 40% | 30% | 30% | Balanced fallback |

In [2]:
# Create bics_sector alias from the Bloomberg classification column
if "bics_sector" not in master.columns:
    master["bics_sector"] = master["classificationLevelName1"]

# SASB materiality weights per BICS sector: (E_weight, S_weight, G_weight)
SASB_WEIGHTS = {
    "Technology":              (0.25, 0.35, 0.40),
    "Financials":              (0.20, 0.35, 0.45),
    "Energy":                  (0.55, 0.25, 0.20),
    "Consumer Discretionary":  (0.35, 0.40, 0.25),
    "Consumer Staples":        (0.35, 0.40, 0.25),
    "Health Care":             (0.25, 0.40, 0.35),
    "Industrials":             (0.45, 0.35, 0.20),
    "Materials":               (0.50, 0.30, 0.20),
    "Real Estate":             (0.45, 0.25, 0.30),
    "Communication Services":  (0.20, 0.40, 0.40),
    "Utilities":               (0.50, 0.25, 0.25),
}
DEFAULT_WEIGHTS = (0.40, 0.30, 0.30)

# Map each company to its sector weights
def get_sasb_weights(sector):
    for key in SASB_WEIGHTS:
        if isinstance(sector, str) and key.lower() in sector.lower():
            return SASB_WEIGHTS[key]
    return DEFAULT_WEIGHTS

master["sasb_e_weight"], master["sasb_s_weight"], master["sasb_g_weight"] = zip(
    *master["bics_sector"].apply(get_sasb_weights)
)

# Show the weight assigned to each sector present in the universe
weight_summary = (
    master[["bics_sector", "sasb_e_weight", "sasb_s_weight", "sasb_g_weight"]]
    .drop_duplicates("bics_sector")
    .sort_values("bics_sector")
    .reset_index(drop=True)
)
print(f"Sectors in universe: {len(weight_summary)}")
print(weight_summary.to_string(index=False))

Sectors in universe: 11
           bics_sector  sasb_e_weight  sasb_s_weight  sasb_g_weight
        Communications           0.40           0.30           0.30
Consumer Discretionary           0.35           0.40           0.25
      Consumer Staples           0.35           0.40           0.25
                Energy           0.55           0.25           0.20
            Financials           0.20           0.35           0.45
           Health Care           0.25           0.40           0.35
           Industrials           0.45           0.35           0.20
             Materials           0.50           0.30           0.20
           Real Estate           0.45           0.25           0.30
            Technology           0.25           0.35           0.40
             Utilities           0.50           0.25           0.25

C:\Users\HP\AppData\Local\Temp\ipykernel_20432\2752441440.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master["bics_sector"] = master["classificationLevelName1"]
C:\Users\HP\AppData\Local\Temp\ipykernel_20432\2752441440.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master["sasb_e_weight"], master["sasb_s_weight"], master["sasb_g_weight"] = zip(
C:\Users\HP\AppData\Local\Temp\ipykernel_20432\2752441440.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master["sasb_e_weight"], master["sasb_s_weight"], master["sasb_g_weight"] = zip(
C:\Users\HP\AppData\Local\Temp\ipykernel_20432\2752441440.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master["sasb_e_weight"], master["sasb_s_weight"], master["sasb_g_weight"] = zip(

## Step 1 â€” Choose which variables to include

After running the cell above, look at the column list and decide which columns belong to E, S, and G.

**Examples of typical columns:**
- **E (Environmental):** GHG emissions, Scope 1, Scope 2, carbon intensity, water usage, energy consumption
- **S (Social):** employee turnover, workplace accidents, gender pay gap, employee training hours
- **G (Governance):** board independence, board gender diversity, CEO pay ratio, audit committee independence

In [3]:
E_VARS = [
    "scope1_emissions_tco2e",
    "carbon_intensity_tco2e_per_eur_m_revenue",
    "renewable_energy_pct",
    "water_withdrawal_m3",
    "waste_recycled_pct",
]

S_VARS = [
    "women_in_workforce_pct",
    "gender_pay_gap_pct",
    "employee_turnover_pct",
    "work_related_injury_rate",
    "training_hours_per_employee",
]

G_VARS = [
    "board_independence_pct",
    "women_on_board_pct",
    "audit_committee_independence_pct",
    "executive_pay_esg_linked_pct",
    "ceo_pay_ratio",
]

# True = lower is better (e.g. emissions), False = higher is better
INVERT = {
    "scope1_emissions_tco2e":                  True,
    "carbon_intensity_tco2e_per_eur_m_revenue": True,
    "renewable_energy_pct":                    False,
    "water_withdrawal_m3":                     True,
    "waste_recycled_pct":                      False,
    "women_in_workforce_pct":                  False,
    "gender_pay_gap_pct":                      True,
    "employee_turnover_pct":                   True,
    "work_related_injury_rate":                True,
    "training_hours_per_employee":             False,
    "board_independence_pct":                  False,
    "women_on_board_pct":                      False,
    "audit_committee_independence_pct":        False,
    "executive_pay_esg_linked_pct":            False,
    "ceo_pay_ratio":                           True,
}

ALL_VARS = E_VARS + S_VARS + G_VARS
print(f"E variables: {len(E_VARS)}")
print(f"S variables: {len(S_VARS)}")
print(f"G variables: {len(G_VARS)}")

E variables: 5
S variables: 5
G variables: 5

## Step 2 â€” Normalise all variables to 0â€“100

We use min-max normalisation: the best company in each variable scores 100, the worst scores 0, everyone else is in between. This makes all variables comparable regardless of their units.

In [4]:
def normalise(series, invert=False):
    """Scale a series to 0-100. If invert=True, lower values get higher scores."""
    mn, mx = series.min(), series.max()
    if mx == mn:
        return pd.Series(50.0, index=series.index)  # all same value â†’ 50
    scaled = (series - mn) / (mx - mn) * 100
    return 100 - scaled if invert else scaled

scores = master[["ticker"] if "ticker" in master.columns else [master.columns[0]]].copy()

# Normalise each variable
for col in ALL_VARS:
    if col in master.columns:
        inv = INVERT.get(col, False)
        scores[f"{col}_score"] = normalise(master[col], invert=inv)
    else:
        print(f"WARNING: Column '{col}' not found in master dataset")

print("Variables normalised.")
scores.head(3)

Variables normalised.

,ticker,scope1_emissions_tco2e_score,carbon_intensity_tco2e_per_eur_m_revenue_score,renewable_energy_pct_score,water_withdrawal_m3_score,waste_recycled_pct_score,women_in_workforce_pct_score,gender_pay_gap_pct_score,employee_turnover_pct_score,work_related_injury_rate_score,training_hours_per_employee_score,board_independence_pct_score,women_on_board_pct_score,audit_committee_independence_pct_score,executive_pay_esg_linked_pct_score,ceo_pay_ratio_score
0,DP4B,71.881770,NaN,0.466497,NaN,NaN,28.415301,NaN,84.354839,NaN,NaN,53.846331,40.000000,100.000000,0.0,97.670185
1,SEBA,99.999999,NaN,0.110385,NaN,57.0,59.677214,NaN,82.258065,NaN,8.176215,37.062550,80.000000,39.999760,0.0,98.953693
2,ALV,99.978109,NaN,0.786808,99.994842,46.6,54.593976,99.99989,75.322581,96.074271,12.337591,42.307914,57.454545,51.999808,100.0,99.614202

## Step 3 â€” Calculate E, S, G and combined ESG scores

We weight each pillar equally (33%/33%/33%) unless you want to change this.  
The combined ESG score is a weighted average of E, S, and G.

In [5]:
def pillar_score(df, variables):
    cols = [f"{v}_score" for v in variables if f"{v}_score" in df.columns]
    if not cols:
        return pd.Series(np.nan, index=df.index)
    return df[cols].mean(axis=1)

scores["E_score"] = pillar_score(scores, E_VARS).round(2)
scores["S_score"] = pillar_score(scores, S_VARS).round(2)
scores["G_score"] = pillar_score(scores, G_VARS).round(2)

# Merge SASB weights into scores
scores = scores.merge(
    master[["ticker", "bics_sector", "sasb_e_weight", "sasb_s_weight", "sasb_g_weight"]],
    on="ticker", how="left"
)

# Ensure numeric dtypes (pandas >= 2.1 no longer silently downcasts object arrays)
for col in ["E_score", "S_score", "G_score",
            "sasb_e_weight", "sasb_s_weight", "sasb_g_weight"]:
    scores[col] = pd.to_numeric(scores[col], errors="coerce")

# Identify companies with NO pillar data at all
all_nan_mask = scores["E_score"].isna() & scores["S_score"].isna() & scores["G_score"].isna()
scores["esg_data_flag"] = "OK"
scores.loc[all_nan_mask, "esg_data_flag"] = "LOW_DATA"

scores["ESG_score"] = (
    scores["E_score"].fillna(scores["E_score"].median()) * scores["sasb_e_weight"] +
    scores["S_score"].fillna(scores["S_score"].median()) * scores["sasb_s_weight"] +
    scores["G_score"].fillna(scores["G_score"].median()) * scores["sasb_g_weight"]
).round(2).astype(float)
scores.loc[all_nan_mask, "ESG_score"] = np.nan

low_data_tickers = scores.loc[all_nan_mask, "ticker"].tolist()
print(f"LOW_DATA companies (all pillars NaN, excluded from portfolio): {low_data_tickers}")

final_scores = scores[[
    "ticker", "bics_sector",
    "E_score", "S_score", "G_score", "ESG_score", "esg_data_flag",
    "sasb_e_weight", "sasb_s_weight", "sasb_g_weight"
]].copy()

# Ensure ESG_score is float for nlargest
final_scores["ESG_score"] = pd.to_numeric(final_scores["ESG_score"], errors="coerce")

print("\nTop 10 by ESG score (SASB-weighted):")
print(final_scores.nlargest(10, "ESG_score")[
    ["ticker", "bics_sector", "E_score", "S_score", "G_score",
     "sasb_e_weight", "sasb_s_weight", "sasb_g_weight", "ESG_score", "esg_data_flag"]
].to_string(index=False))

LOW_DATA companies (all pillars NaN, excluded from portfolio): ['FTD', '1ZG', '7CA', '2X1']

Top 10 by ESG score (SASB-weighted):
ticker            bics_sector  E_score  S_score  G_score  sasb_e_weight  sasb_s_weight  sasb_g_weight  ESG_score esg_data_flag
   NXG Consumer Discretionary    98.99    76.66    87.15           0.35           0.40           0.25      87.10            OK
  IHCB                 Energy   100.00    51.22    95.82           0.55           0.25           0.20      86.97            OK
   7MP             Financials   100.00    73.10    88.84           0.20           0.35           0.45      85.56            OK
  SKWA              Materials    95.11    61.19    78.57           0.50           0.30           0.20      81.63            OK
  EFEA            Real Estate   100.00    85.48    50.33           0.45           0.25           0.30      81.47            OK
  QS2A            Industrials    99.99    66.84    64.82           0.45           0.35           0.20      81.35            OK
   G1A            Industrials    94.32    75.37    62.57           0.45           0.35           0.20      81.34            OK
   ECN            Industrials    82.00    75.72    86.48           0.45           0.35           0.20      80.70            OK
  B4M1             Financials   100.00    73.35    74.92           0.20           0.35           0.45      79.39            OK
  EOAN              Utilities    92.67    57.30    74.88           0.50           0.25           0.25      79.38            OK

## Step 4 â€” ESG Triangulation

We cross-check our own ESG score against two external sources:
- **Bloomberg ESG Disclosure Score** â€” from the professor's provided CSV. Measures how completely a company discloses ESG data. Range 0â€“100, higher is better. Threshold: â‰¥ 50 = PASS.
- **Sustainalytics Risk Score** â€” fetched via yfinance (Yahoo Finance ESG tab). Measures unmanaged ESG risk. Range 0â€“100, **lower is better**. Threshold: â‰¤ 30 (medium risk or below) = PASS.

**Rule:** a company must pass at least **2 of 3** sources to clear triangulation. Companies that pass only 1 or fewer are flagged as **WATCHLIST** â€” they remain in the universe but are flagged for manual review before final selection.

| Source | Pass condition | Rationale |
|--------|---------------|----------|
| Agent score | â‰¥ 50 / 100 | Above-median in our own scoring |
| Bloomberg ESG Disclosure | â‰¥ 50 / 100 | Sufficient ESG transparency |
| Sustainalytics Risk | â‰¤ 30 / 100 | Medium risk or below |

In [6]:
import yfinance as yf
import time

# Source 2: Bloomberg ESG Disclosure Score
# Use idBbCompany (unique per company) to avoid ticker ambiguity
target_ids = set(master["idBbCompany"].dropna().astype(int).tolist())
esg_raw = pd.read_csv("../data/provided/esgEnvironmentalSocialConsolidatedV4.csv",
                      usecols=["idBbCompany", "esgDisclosureScore"])
esg_raw = esg_raw[esg_raw["idBbCompany"].isin(target_ids)].dropna(subset=["esgDisclosureScore"])
esg_raw = esg_raw.drop_duplicates("idBbCompany", keep="last")

id_to_ticker = master[["idBbCompany", "ticker"]].dropna().drop_duplicates("idBbCompany")
bloomberg_esg = id_to_ticker.merge(esg_raw, on="idBbCompany", how="left")
bloomberg_esg = bloomberg_esg[["ticker", "esgDisclosureScore"]].rename(
    columns={"esgDisclosureScore": "bloomberg_esg_disclosure"}
)
n_matched = bloomberg_esg["bloomberg_esg_disclosure"].notna().sum()
print(f"Bloomberg ESG disclosure matched: {n_matched} / {len(bloomberg_esg)} companies")

# Source 3: Sustainalytics via yfinance (use yf_ticker, not Bloomberg ticker)
yf_map = master[["ticker", "yf_ticker"]].dropna(subset=["yf_ticker"]).drop_duplicates("ticker")
print(f"Fetching Sustainalytics for {len(yf_map)} tickers...")

sust_rows = []
for i, row in enumerate(yf_map.itertuples(), 1):
    try:
        sust = yf.Ticker(row.yf_ticker).sustainability
        score = sust.loc["totalEsg", "Value"] if (sust is not None and "totalEsg" in sust.index) else None
    except Exception:
        score = None
    sust_rows.append({"ticker": row.ticker, "sustainalytics_risk_score": score})
    if i % 10 == 0:
        print(f"  {i}/{len(yf_map)} done...")
        time.sleep(1)

sust_df = pd.DataFrame(sust_rows)
n_sust = sust_df["sustainalytics_risk_score"].notna().sum()
print(f"Sustainalytics fetched: {n_sust} / {len(sust_df)} companies")

# Merge all three sources (all joins on Bloomberg ticker â€” 1:1 with final_scores)
tri = (
    final_scores[["ticker", "ESG_score"]]
    .merge(bloomberg_esg, on="ticker", how="left")
    .merge(sust_df,       on="ticker", how="left")
)

AGENT_THRESHOLD          = 50
BLOOMBERG_THRESHOLD      = 50
SUSTAINALYTICS_THRESHOLD = 30

tri["agent_pass"]          = tri["ESG_score"] >= AGENT_THRESHOLD
tri["bloomberg_pass"]      = tri["bloomberg_esg_disclosure"] >= BLOOMBERG_THRESHOLD
tri["sustainalytics_pass"] = tri["sustainalytics_risk_score"] <= SUSTAINALYTICS_THRESHOLD

tri["tri_sources_available"] = (
    tri["ESG_score"].notna().astype(int) +
    tri["bloomberg_esg_disclosure"].notna().astype(int) +
    tri["sustainalytics_risk_score"].notna().astype(int)
)
tri["tri_passes"] = (
    tri["agent_pass"].fillna(False).astype(int) +
    tri["bloomberg_pass"].fillna(False).astype(int) +
    tri["sustainalytics_pass"].fillna(False).astype(int)
)

def triangulation_result(row):
    if row["tri_sources_available"] < 2:
        return "LOW_DATA"
    return "PASS" if row["tri_passes"] >= 2 else "WATCHLIST"

tri["triangulation_result"] = tri.apply(triangulation_result, axis=1)

final_scores = final_scores.merge(
    tri[["ticker", "bloomberg_esg_disclosure", "sustainalytics_risk_score",
         "tri_sources_available", "tri_passes", "triangulation_result"]],
    on="ticker", how="left"
)

print("Triangulation results:")
print(final_scores["triangulation_result"].value_counts().to_string())
print()
watchlist = final_scores[final_scores["triangulation_result"] == "WATCHLIST"]
print(f"WATCHLIST ({len(watchlist)} companies):")
print(watchlist[["ticker", "ESG_score", "bloomberg_esg_disclosure",
                  "sustainalytics_risk_score", "tri_passes"]].to_string(index=False))

Bloomberg ESG disclosure matched: 275 / 279 companies
Fetching Sustainalytics for 279 tickers...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MAERSK-B.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SEB-A.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ALV.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RXL.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ISP.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RWE.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NDA.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CBK.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DBK.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: GBF.DE"}}}

  10/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HEI.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HOT.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SDF.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SIE.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MUV2.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MC.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: UCG.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VER.VI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: OR.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: OMV.VI"}}}

  20/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SRT3.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IBE.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: REP.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SSE.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AIXA.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BKT.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: INGA.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CS.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RIO.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VOLV-B.ST"}}}

  30/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SCYR.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KPN.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TSCO.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LSEG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: GLE.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BNP.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AGN.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: G.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ORA.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SU.PA"}}}

  40/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AI.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AD.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RTO.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SHB-A.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BCP.LS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NOKIA.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BESI.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TIT.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: UU.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ASML.AS"}}}

  50/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SCMN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DTE.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BEAN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DANSKE.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TTE.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CNA.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NHY.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ELE.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LOGN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IAG.L"}}}

  60/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SUN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NXT.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: INVE-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: STMMI.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TEL2-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MKS.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NWG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SQN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: EBS.VI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CDI.PA"}}}

  70/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: STAN.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KBC.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: UCB.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SIKA.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ASM.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ARCAD.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SRP.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SAND.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MAP.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: EN.PA"}}}

  80/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: JYSK.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IMI.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NEM.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ABBN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HSBA.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DB1.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: INVP.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SUBC.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FGR.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MYCR.ST"}}}

  90/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NDX1.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AAL.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BZU.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LONN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ENEL.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DSV.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BBY.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RS1.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ALFA.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PUB.PA"}}}

  100/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: UNI.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IP.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ANA.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MTO.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SBMO.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SMIN.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: EQNR.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ATCO-A.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SAGA-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IFX.DE"}}}

  110/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: III.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KRX.IR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KESKOB.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CFR.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: STMN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AV.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TREL-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: A2A.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: EOAN.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VIE.PA"}}}

  120/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: WRT1V.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HNR1.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AZN.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BARC.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HBAN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LLOY.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SLHN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ZURN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FRO.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KCR.HE"}}}

  130/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SWED-A.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NKT.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FHZN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HUBN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RMS.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TLX.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: G1A.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: REY.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HOLM-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ENI.MI"}}}

  140/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FNTN.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FER.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SAB.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NEX.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ANDR.VI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HOLN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BP.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NOVN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VK.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DIE.BR"}}}

  150/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ACA.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AGS.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ACKB.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: STB.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: INDU-C.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SSAB-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BGN.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PAF.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ANTO.L"}}}

  160/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IHG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SB1NO.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TRN.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IPN.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AZM.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: INDT.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HOC.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PSPN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NESTE.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RBI.VI"}}}

  170/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ELI.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MOBN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MT.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ENGI.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BOL.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SOBI.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HSX.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ORNBV.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PGHN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LR.PA"}}}

  180/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TEN.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ALSYDB.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VZN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IGG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ICG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FLS.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SPSN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: METSO.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TUB.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CABK.MC"}}}

  190/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ADDT-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PRY.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SALM.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DIM.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ALK-B.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FRES.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FTK.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LOOMIS.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VATN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BCVN.SW"}}}

  200/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KBCA.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BAER.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BPE.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: HLMA.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AKRBP.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LAGR-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ZEAL.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NOD.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SREN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BKW.SW"}}}

  210/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BC.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PKO.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ACP.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PKN.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PZU.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TPE.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MBK.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PEO.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: KGH.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: GAW.L"}}}

  220/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CDR.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CCH.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MONC.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VALMT.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: GTT.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SFZN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ISS.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PLUS.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AMUN.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ENX.PA"}}}

  230/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IMCD.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NN.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: FBK.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ARGX.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SPIE.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LIFCO-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: UBSG.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AENA.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ELIS.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CLNX.MC"}}}

  240/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ZEG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: PST.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RACE.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: CAMX.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BMED.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: VACN.SW"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ASRNL.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: IG.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BAMI.MI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: GALE.SW"}}}

  250/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ABVX.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: UNI.MC"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BIRG.IR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BG.VI"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: A5G.IR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LPP.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BEZ.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BGEO.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ING.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SWEC-B.ST"}}}

  260/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AZA.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: NDA-FI.HE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DPLM.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BEIJ-B.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: LOTB.BR"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: EMG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: AAF.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: MNG.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: ENR.DE"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SECT-B.ST"}}}

  270/279 done...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SAVE.ST"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TE.PA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TCAP.L"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: BFT.WA"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: DNB.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: RILBA.CO"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SHELL.AS"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: SBNOR.OL"}}}

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: TBCG.L"}}}

Sustainalytics fetched: 0 / 279 companies
Triangulation results:
triangulation_result
PASS         165
WATCHLIST    110
LOW_DATA       4

WATCHLIST (110 companies):
ticker  ESG_score  bloomberg_esg_disclosure sustainalytics_risk_score  tri_passes
  DP4B      47.67                     58.41                      None           1
   GBF      52.76                     40.84                      None           1
  TCO0      62.39                     48.12                      None           1
  RTO1      66.66                     48.12                      None           1
   BSI      51.79                     44.28                      None           1
   DTE      44.33                     56.00                      None           1
   8RJ      42.31                     50.84                      None           1
  SUL1      69.31                     46.10                      None           1
   IVS      62.09                     38.26                      None           1
  NCYD      64.90                     48.00                      None           1
   1SQ      76.37                     35.21                      None           1
   KDB      44.03                     54.19                      None           1
  SIKA      48.80                     57.87                      None           1
   AVS      76.91                     49.52                      None           1
  HIJ2      61.57                     43.87                      None           1
   BYG      62.88                     49.83                      None           1
  JYS1      59.23                     30.99                      None           1
  IMI1      70.20                     46.95                      None           1
   NEM      56.38                     25.07                      None           1
   EF3      58.92                     49.51                      None           1
   MLT      66.02                     45.35                      None           1
  NDX1      57.84                     48.76                      None           1
   UCM      41.81                     60.30                      None           1
  DS81      59.24                     47.47                      None           1
   8IG      62.00                     33.03                      None           1
  EFEA      81.47                     40.16                      None           1
  QS51      56.93                     45.41                      None           1
  TLLB      45.70                     52.57                      None           1
  HNR1      51.46                     46.88                      None           1
   HF6      64.04                     30.35                      None           1
   NKT      59.03                     49.52                      None           1
  UZAA      71.32                     34.85                      None           1
  HGUA      54.35                     45.38                      None           1
  REJA      50.27                     21.42                      None           1
  FNTN      68.58                     48.83                      None           1
   NXS      44.55                     54.70                      None           1
  DJDA      45.19                     52.45                      None           1
  FO4N      64.52                     36.97                      None           1
   B3K      76.98                     32.68                      None           1
   SKT      60.52                     40.27                      None           1
  IDVA      59.80                     35.55                      None           1
  B4M1      79.39                     37.56                      None           1
   HDB      38.95                     39.17                      None           0
   I1M      67.15                     38.09                      None           1
   H3M      59.94                     43.62                      None           1
   P7S      63.24                     43.58                      None           1
   E4S      64.21                     45.60                      None           1
   M1H      69.45                     47.46                      None           1
  ARRD      46.62                     61.73                      None           1
   B6E      67.35                     42.44                      None           1
  H2X3      51.68                     46.55                      None           1
   P2H      66.53                     45.04                      None           1
  TW11      78.44                     48.48                      None           1
   TM2      74.35                     45.80                      None           1
  IHJN      57.87                     21.93                      None           1
   I5G      61.77                     46.91                      None           1
  I2X2      58.71                     49.91                      None           1
  AZZ2      50.71                     45.48                      None           1
   JEP      43.17                     44.28                      None           0
  56S1      38.06                     58.82                      None           1
  4AJ0      64.92                     49.16                      None           1
   FTK      57.14                     21.51                      None           1
  K900      58.87                     27.23                      None           1
   VAT      66.76                     41.48                      None           1
  B1V1      66.55                     48.15                      None           1
   KB9      47.75                     27.19                      None           0
  LG72      55.65                     31.88                      None           1
   22Z      68.05                     34.78                      None           1
   N0S      69.40                     36.23                      None           1
   B9W      66.08                     28.68                      None           1
   P9O      76.85                     46.82                      None           1
  SFB1      54.79                     24.60                      None           1
  PKY1      74.15                     49.90                      None           1
   7PZ      69.77                     46.51                      None           1
   1T5      52.40                     45.02                      None           1
   BRU      60.86                     44.03                      None           1
   BP1      70.84                     39.18                      None           1
  KGHA      60.66                     47.69                      None           1
   G7W      76.29                     44.13                      None           1
   7CD      65.85                     21.30                      None           1
   9TG      74.59                     43.59                      None           1
   P55      66.09                     39.62                      None           1
   1AE      63.40                     32.31                      None           1
   4SP      49.31                     45.82                      None           0
  1L30      67.68                     37.23                      None           1
   7EL      49.67                     57.34                      None           1
   19V      63.95                     41.54                      None           1
   7UB      64.26                     45.14                      None           1
  BIRG      69.56                     45.95                      None           1
   1RY      71.31                     44.86                      None           1
   2D7      49.90                     42.62                      None           0
   GEB      70.50                     45.72                      None           1
   6GF      63.72                     46.15                      None           1
  7W71      56.56                     35.99                      None           1
  1JJA      62.81                     32.38                      None           1
   04Q      66.10                     43.02                      None           1
   DP9      73.51                     46.40                      None           1
  BRZ0      56.45                     38.38                      None           1
   7LB      57.68                     33.29                      None           1
   M3N      67.36                     48.79                      None           1
   9AA      61.73                     38.20                      None           1
  61L0      59.76                     29.74                      None           1
   9JL      52.19                     35.01                      None           1
   68F      67.84                     44.55                      None           1
   8D7      59.54                     45.13                      None           1
   3ZV      58.54                     18.73                      None           1
  D1NC      65.24                     49.40                      None           1
   CJ2      73.30                     24.18                      None           1
   K7I      32.40                     30.10                      None           0
  TBCG      68.28                     45.45                      None           1

## Step 5 â€” WACI (Weighted Average Carbon Intensity)

WACI is the standard carbon metric required by the assignment.  
It measures how carbon-intensive the portfolio is, weighted by how much we invest in each company.  
Unit: tonnes of COâ‚‚ per million euros of revenue (tCOâ‚‚e / â‚¬m revenue)

In [7]:
# Carbon intensity: use Bloomberg Calc value where available,
# fall back to sector median for missing companies.
# Bloomberg co2IntensityPerSalesCalc is an estimated/modelled field.
# Imputed values are flagged ci_source = sector_median_imputed.

CARBON_COL   = "carbon_intensity_tco2e_per_eur_m_revenue"
SECTOR_COL_W = "classificationLevelName1"

ci = master[["ticker", CARBON_COL, SECTOR_COL_W]].drop_duplicates("ticker").copy()
ci.columns = ["ticker", "carbon_intensity", "sector"]

# Compute sector medians from reported values
sector_medians = ci.dropna(subset=["carbon_intensity"]).groupby("sector")["carbon_intensity"].median()
global_median  = ci["carbon_intensity"].median()

print("Sector median carbon intensity (tCO2e/EUR m revenue):")
for sector, median in sector_medians.sort_values(ascending=False).items():
    n_reported = ci[ci["sector"] == sector]["carbon_intensity"].notna().sum()
    n_total    = (ci["sector"] == sector).sum()
    print(f"  {sector:<30} {median:>8.1f}  ({n_reported}/{n_total} reported)")

# Impute missing values with sector median (or global if sector has no data)
def impute_ci(row):
    if pd.notna(row["carbon_intensity"]):
        return row["carbon_intensity"], "bloomberg_calc"
    fallback = sector_medians.get(row["sector"], global_median)
    return fallback, "sector_median_imputed"

ci[["carbon_intensity", "ci_source"]] = ci.apply(
    lambda r: pd.Series(impute_ci(r)), axis=1
)

n_reported = (ci["ci_source"] == "bloomberg_calc").sum()
n_imputed  = (ci["ci_source"] == "sector_median_imputed").sum()
print(f"\nCoverage: {n_reported} reported, {n_imputed} sector-median imputed")
print(f"\nTop 10 highest carbon intensity:")
print(ci.sort_values("carbon_intensity", ascending=False)[["ticker","carbon_intensity","ci_source"]].head(10).to_string(index=False))

Sector median carbon intensity (tCO2e/EUR m revenue):
  Materials                        4134.0  (4/23 reported)
  Utilities                         629.8  (1/18 reported)
  Energy                            144.7  (4/15 reported)
  Consumer Staples                   85.4  (1/8 reported)
  Health Care                        15.7  (4/20 reported)
  Industrials                         9.8  (8/60 reported)
  Financials                          0.7  (7/94 reported)
  Consumer Discretionary              0.0  (1/12 reported)

Coverage: 30 reported, 249 sector-median imputed

Top 10 highest carbon intensity:

ticker  carbon_intensity             ci_source
   UCM           6439.03        bloomberg_calc
  HLBN           4285.61        bloomberg_calc
  NOH1           4134.00 sector_median_imputed
  KGHA           4134.00 sector_median_imputed
   AIL           4134.00 sector_median_imputed
  VACD           4134.00 sector_median_imputed
  HL9C           4134.00 sector_median_imputed
   SDF           4134.00 sector_median_imputed
   NDA           4134.00 sector_median_imputed
   RTZ           4134.00 sector_median_imputed

## Step 6 â€” Save ESG scores

In [8]:
today = str(date.today())

# Merge carbon intensity + imputation source into ESG scores
if "carbon_intensity" in ci.columns:
    final_scores = final_scores.merge(
        ci[["ticker", "carbon_intensity", "ci_source"]], on="ticker", how="left"
    )

final_scores["data_vintage"] = today
out_path = f"../outputs/scores/esg_scores_{today}.csv"
final_scores.to_csv(out_path, index=False)
print(f"ESG scores saved: {out_path}")
print(f"Columns: {list(final_scores.columns)}")
print("\nScore summary:")
final_scores[["E_score","S_score","G_score","ESG_score"]].describe().round(2)

ESG scores saved: ../outputs/scores/esg_scores_2026-05-20.csv
Columns: ['ticker', 'bics_sector', 'E_score', 'S_score', 'G_score', 'ESG_score', 'esg_data_flag', 'sasb_e_weight', 'sasb_s_weight', 'sasb_g_weight', 'bloomberg_esg_disclosure', 'sustainalytics_risk_score', 'tri_sources_available', 'tri_passes', 'triangulation_result', 'carbon_intensity', 'ci_source', 'data_vintage']

Score summary:

       E_score  S_score  G_score  ESG_score
count   256.00   264.00   275.00     275.00
mean     72.47    53.01    66.12      63.68
std      19.47    16.76    15.76       9.23
min       0.00     0.00     0.00      32.40
25%      58.22    43.60    55.43      58.03
50%      67.79    53.74    65.34      63.72
75%      93.18    64.45    75.78      69.79
max     100.00    92.18    99.98      87.10

## Notebook complete

You now have:
- **SASB materiality weights** per sector
- **E, S, G and combined ESG scores** (0â€“100), sector-weighted
- **ESG Triangulation** â€” Bloomberg disclosure + Sustainalytics cross-check, 2-of-3 rule
- **WATCHLIST flags** for companies that fail triangulation
- **Carbon intensity** per company

Output files:
- `outputs/scores/esg_scores_DATE.csv` â€” full ESG scores with triangulation columns

**Next:** Open `agent11_portfolio_construction.ipynb` to select the final 15â€“25 holdings.

---

## Step 7 — Import FactSet ESG data from ESG Specialist

Replaces the broken in-house triangulation (Bloomberg Disclosure + broken yfinance Sustainalytics)
with the specialist's proper FactSet output: **Truvalue + Sustainalytics + ISS** (2-of-3 rule).

**Source files** (in `data/provided/`):
- `Portfolio_Screening_Output.xlsx` — Stage 1 vendor screening (289 companies), hard exclusions list, Stage 2 full ranking with E/S/G pillar z-scores
- `stage2_top40_capped_hybrid.csv` — sector-capped top 40 (reference / sanity check)

**Output:** saves a new `esg_scores_{today}.csv` which NB10 automatically picks up (it globs for the latest file).

**How to run:** execute the cell below independently — you do NOT need to re-run the full NB05 pipeline first. The cell reads the specialist's files and the current master dataset, then writes the new ESG scores file.

In [9]:
import pandas as pd
import numpy as np
import re
import glob
from datetime import date

TODAY = str(date.today())
PORTFOLIO_FILE = "../data/provided/Portfolio_Screening_Output.xlsx"

# ── 1. Load specialist sheets ─────────────────────────────────────────────────
s1_all    = pd.read_excel(PORTFOLIO_FILE, sheet_name="Stage 1 — Universe")
hard_raw  = pd.read_excel(PORTFOLIO_FILE, sheet_name="Hard exclusions detail")
s2_full   = pd.read_excel(PORTFOLIO_FILE, sheet_name="Stage 2 — Full ranking")
hard_excl_names = set(hard_raw["Company"].str.strip().str.lower())

print(f"Stage 1 universe: {len(s1_all)} companies")
print(f"Hard exclusions:  {len(hard_raw)} companies")
print(f"Stage 2 ranked:   {len(s2_full)} companies")

# ── 2. Load master dataset for ticker mapping ─────────────────────────────────
master_files = sorted(glob.glob("../outputs/scores/master_dataset_*.csv"))
master = pd.read_csv(master_files[-1], usecols=["ticker", "yf_ticker", "idBbGlobalCompanyName",
                                                  "carbon_intensity_tco2e_per_eur_m_revenue",
                                                  "classificationLevelName1"])
master = master.drop_duplicates("ticker")
print(f"Master dataset:   {len(master)} companies")

# ── 3. Company name normalisation ─────────────────────────────────────────────
_SUFFIXES = sorted([
    "class b", "class a", "class c", "ab", "sa", "nv", "plc", "ag", "asa",
    "oyj abp", "oyj", "oy", "ltd", "inc", "corp", "spa", "s p a", "s a",
    "se", "a s", "as", "group", "holding", "holdings", "sca", "psc",
], key=len, reverse=True)

def norm(s):
    s = re.sub(r"[^\w\s]", " ", str(s).lower())
    s = re.sub(r"\s+", " ", s).strip()
    for sfx in _SUFFIXES:
        if s.endswith(" " + sfx):
            s = s[: -len(sfx) - 1].strip()
            break
    return s

master["_key"]  = master["idBbGlobalCompanyName"].apply(norm)
s1_all["_key"]  = s1_all["Company"].apply(norm)
s2_full["_key"] = s2_full["Company"].apply(norm)

# ── 4. Join Stage 1 universe → master ticker ──────────────────────────────────
merged = s1_all.merge(
    master[["_key", "ticker", "yf_ticker", "carbon_intensity_tco2e_per_eur_m_revenue",
            "classificationLevelName1"]],
    on="_key", how="left"
)

n_matched = merged["ticker"].notna().sum()
unmatched = merged.loc[merged["ticker"].isna(), "Company"].tolist()
print(f"\nMatched {n_matched}/{len(merged)} specialist companies to master ticker")
if unmatched:
    print(f"Unmatched (not in current master — no financial data yet): {unmatched[:10]}")

# ── 5. Add Stage 2 ranking scores ─────────────────────────────────────────────
s2_scores = s2_full[["_key", "Rank", "In-house ESG z", "Percentile",
                      "E pillar", "S pillar", "G pillar",
                      "Watchlist", "Watchlist reason"]].rename(columns={
    "Rank": "esg_rank", "In-house ESG z": "in_house_z",
    "Percentile": "in_house_pct",
    "E pillar": "E_z", "S pillar": "S_z", "G pillar": "G_z",
    "Watchlist": "watchlist", "Watchlist reason": "watchlist_reason",
})
merged = merged.merge(s2_scores, on="_key", how="left")

# ── 6. Normalise E/S/G pillar z-scores → 0–100 ───────────────────────────────
for z_col, out_col in [("E_z", "E_score"), ("S_z", "S_score"), ("G_z", "G_score")]:
    z = merged[z_col]
    z_min, z_max = z.min(), z.max()
    if z_max > z_min:
        merged[out_col] = ((z - z_min) / (z_max - z_min) * 100).clip(0, 100).round(2)
    else:
        merged[out_col] = 50.0
    merged[out_col] = merged[out_col].fillna(0.0)

# ── 7. Hard-excluded flag and final ESG_score ─────────────────────────────────
merged["hard_excluded"]  = merged["Company"].str.strip().str.lower().isin(hard_excl_names)
merged["fossil_flag"]    = merged["Fossil flag"].fillna(False).astype(bool)

# ESG_score = in_house_pct (0–100 percentile) for Stage 2 companies
# Stage 1 failures and hard exclusions get 0 — they fall below ESG_FLOOR in NB10
merged["ESG_score"] = np.where(
    merged["Stage 1 PASS"] & ~merged["hard_excluded"],
    merged["in_house_pct"].fillna(0.0),
    0.0
).round(2)

# ── 8. Carbon intensity: use master value, fall back to sector median ─────────
ci_col = "carbon_intensity_tco2e_per_eur_m_revenue"
sector_median = (
    merged.dropna(subset=[ci_col])
    .groupby("classificationLevelName1")[ci_col]
    .median()
)
global_median = merged[ci_col].median()

def get_ci(row):
    if pd.notna(row[ci_col]):
        return row[ci_col], "bloomberg_calc"
    fallback = sector_median.get(row["classificationLevelName1"], global_median)
    return (fallback if pd.notna(fallback) else global_median), "sector_median_imputed"

merged[["carbon_intensity", "ci_source"]] = merged.apply(
    lambda r: pd.Series(get_ci(r)), axis=1
)

# ── 9. Assemble output columns ────────────────────────────────────────────────
out = merged[[
    "ticker", "yf_ticker", "Company", "SASB Sector",
    "Truvalue", "SA Risk", "SA Band", "ISS",
    "PASS votes", "FAIL votes", "Stage 1 vendor verdict", "Stage 1 PASS",
    "fossil_flag", "hard_excluded", "watchlist", "watchlist_reason",
    "esg_rank", "in_house_z", "in_house_pct",
    "E_score", "S_score", "G_score", "ESG_score",
    "carbon_intensity", "ci_source",
]].rename(columns={
    "Company":                 "company_name",
    "SASB Sector":             "sasb_sector",
    "Truvalue":                "truvalue_rating",
    "SA Risk":                 "sa_risk",
    "SA Band":                 "sa_band",
    "ISS":                     "iss_descriptor",
    "PASS votes":              "tri_pass_votes",
    "FAIL votes":              "tri_fail_votes",
    "Stage 1 vendor verdict":  "triangulation_result",
    "Stage 1 PASS":            "stage1_pass",
})

# Only keep rows where we have a project ticker (i.e., company is in master)
out_matched = out[out["ticker"].notna()].copy()
out_matched["data_vintage"] = TODAY

# ── 10. Save ──────────────────────────────────────────────────────────────────
out_path = f"../outputs/scores/esg_scores_{TODAY}.csv"
out_matched.to_csv(out_path, index=False)

print(f"\n✓ Saved: {out_path}")
print(f"  Companies with ticker match: {len(out_matched)}")
print(f"  Stage 1 PASS:               {out_matched['stage1_pass'].sum()}")
print(f"  Hard excluded:              {out_matched['hard_excluded'].sum()}")
print(f"  Fossil flagged:             {out_matched['fossil_flag'].sum()}")
print(f"  Watchlist:                  {out_matched['watchlist'].sum()}")
print(f"\nESG_score distribution (matched companies):")
print(out_matched["ESG_score"].describe().round(2))
print(f"\nTop 15 by ESG_score:")
print(out_matched[["company_name", "ESG_score", "triangulation_result", "watchlist", "truvalue_rating"]]
      .sort_values("ESG_score", ascending=False)
      .head(15)
      .to_string(index=False))

Stage 1 universe: 289 companies
Hard exclusions:  13 companies
Stage 2 ranked:   224 companies
Master dataset:   279 companies

Matched 213/289 specialist companies to master ticker
Unmatched (not in current master — no financial data yet): ['A.P. Moller - Maersk A/S Class B', 'BE Semiconductor Industries N.V.', 'ABN AMRO Bank N.V. Depositary receipts', 'Addtech AB Class B', 'ALK-abello A/S Class B', 'ASM International N.V.', 'ASR Nederland N.V.', 'Gaztransport & Technigaz', 'Logitech', 'BELIMO']

✓ Saved: ../outputs/scores/esg_scores_2026-05-20.csv
  Companies with ticker match: 213
  Stage 1 PASS:               179
  Hard excluded:              11
  Fossil flagged:             17
  Watchlist:                  24

ESG_score distribution (matched companies):
count    213.00
mean      42.99
std       33.03
min        0.00
25%        6.33
50%       43.04
75%       71.31
max      100.00
Name: ESG_score, dtype: float64

Top 15 by ESG_score:
                    company_name  ESG_score triangulation_result watchlist truvalue_rating
Raiffeisen Bank International AG     100.00                 PASS     False         Average
                   Alfa Laval AB      99.58                 PASS     False         Average
                 Norsk Hydro ASA      99.16                 PASS      True   Below Average
                      Aegon Ltd.      98.31                 PASS     False         Average
                   AIB Group plc      97.89                 PASS      True   Below Average
        Lloyds Banking Group plc      97.47                 PASS     False         Average
                 SBM Offshore NV      97.05                 PASS     False         Average
      Zurich Insurance Group Ltd      96.62                 PASS     False         Average
               NatWest Group Plc      96.20                 PASS     False         Average
                     Swiss Re AG      95.36                 PASS     False         Average
                   VZ Holding AG      94.94                 PASS     False         Average
       Bank of Ireland Group Plc      94.51                 PASS     False         Average
                       Aviva plc      94.09                 PASS     False         Average
               HSBC Holdings Plc      93.25                 PASS     False         Average
                         M&G Plc      92.83                 PASS     False         Average